Repository deckgo/deckdeckgo, pull requests merged in 2019-09, with the labels that each got.

#276 feat(#248): display deck name in title while editing a presentation
  studio/src/app/components/core/app-navigation/app-navigation.scss
  studio/src/app/components/core/app-navigation/app-navigation.tsx
Labels: enhancement

#277 feat(#256): remove debounce when entering tags and prevent enter
  studio/src/app/components/editor/publish/app-publish-edit/app-publish-edit.tsx
Labels: enhancement

#278 feat(#249): sort deck by updated dates rather than created
  studio/src/app/components/core/app-menu/app-menu.tsx
  studio/src/app/services/data/deck/deck.service.tsx
Labels: enhancement

#279 feat(#263): when switching to fullscreen mode, presenting mode per default not the edition mode
  studio/src/app/pages/editor/app-editor/app-editor.tsx
Labels: enhancement

#281 inline-editor: debounce to solve tools appearing on continuing selection
  CHANGELOG.md
  studio/package-lock.json
  studio/package.json
  webcomponents/inline-editor/CHANGELOG.md
  webcomponents/inline-editor/package-lock.json
  webcomponents/inline-editor/package.json
  webcomponents/inline-editor/src/components/inline-editor/deckdeckgo-inline-editor.scss
  webcomponents/inline-editor/src/components/inline-editor/deckdeckgo-inline-editor.tsx
  webcomponents/utils/CHANGELOG.md
  webcomponents/utils/package-lock.json
  webcomponents/utils/package.json
  webcomponents/utils/src/utils/deckdeckgo-utils.ts
Labels: bug

#282 feat(#250): highlight selected element
  studio/src/app/components/editor/app-editor-toolbar/app-editor-toolbar.tsx
  studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
  studio/src/app/utils/editor/reveal-slot.utils.tsx
  studio/src/global/theme/editor/editor-deck-placeholder.scss
  studio/src/global/theme/editor/editor-fullscreen.scss
Labels: enhancement

#284 fix(#283): webpack markdown plugin remarkable import
  webpack/src/markdown/deckdeckgo-markdown-plugin.ts
Labels: bug

#288 fix(#287): toggle fullscreen with Escape
  studio/src/app/pages/editor/app-editor/app-editor.tsx
Labels: bug

#290 feat(#289): try to publish slides not concurrently
  studio/src/app/services/editor/publish/publish.service.tsx
Labels: bug

#291 fix(#243): if deck is published, delete slide in the API too
  studio/src/app/components/editor/app-editor-toolbar/app-editor-toolbar.tsx
  studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
Labels: enhancement

#292 style(#285): inherit caret color
  studio/src/global/theme/content-editable.scss
Labels: enhancement

#295 fix: don't persist reveal list with the content
  studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
Labels: enhancement, studio

#296 fix twitter url typo
  studio/src/app/pages/core/app-settings/app-settings.tsx
Labels: enhancement

#301 feat(#300): improve slide height on mobile devices when browsers are used
  webcomponents/core/src/components/deck/deckdeckgo-deck/deckdeckgo-deck.scss
Labels: enhancement

#303 fix(#302): usage of "hydrated" as word in the content should be possible
  studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
  studio/src/app/utils/editor/reveal-slot.utils.tsx
  studio/src/global/theme/editor/editor-deck-deck.scss
  studio/src/global/theme/editor/editor-deck-placeholder.scss
  studio/src/global/theme/editor/editor-fullscreen.scss
Labels: bug

#305 fix(#298): missing promise resolve
  studio/src/app/pages/core/app-settings/app-settings.tsx
Labels: bug

#306 Infra logging, user PUT fix and DB migration
  infra/handler/app/Handler.hs
  infra/handler/app/Test.hs
  infra/handler/src/DeckGo/Handler.hs
Labels: bug

#308 fix(#307): if empty, delete content field from slide in the db
  studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
  studio/src/app/pages/core/app-signin/app-signin.tsx
Labels: bug

#311 feat: add social links as footer in the menu
  studio/src/app/components/core/app-footer/app-footer.scss
  studio/src/app/components/core/app-footer/app-footer.tsx
Labels: enhancement

#312 docs: add some information about contributing
  CONTRIBUTING.md
Labels: docs

#315 breaking: delete decks, slides and storage on delete users and use firebase_id as root for the storage
  cloud/functions/src/index.ts
  cloud/functions/src/model/deck.ts
  cloud/functions/src/model/slide.ts
  cloud/functions/src/watch/delete/delete-decks-slides.ts
  cloud/functions/src/watch/delete/delete-user-storage.ts
  cloud/functions/src/watch/screenshot/generate-deck-screenshot.ts
  cloud/functions/src/watch/watch-deck-write.ts
  cloud/functions/src/watch/watch-user-delete.ts
  studio/src/app/modals/core/app-user-delete.tsx
  studio/src/app/pages/core/app-settings/app-settings.tsx
  studio/src/app/services/storage/storage.service.tsx
Labels: breaking, studio

#316 studio: add an on demand action to delete presentations
  cloud/functions/src/index.ts
  cloud/functions/src/watch/delete/delete-deck-slides.ts
  cloud/functions/src/watch/delete/delete-decks-slides.ts
  cloud/functions/src/watch/delete/utils/delete-slides-utils.ts
  cloud/functions/src/watch/watch-deck-write.ts
  cloud/functions/src/watch/watch-deck.ts
  cloud/functions/src/watch/watch-user.ts
  studio/src/app/components/core/app-delete-deck-action/app-delete-deck-action.scss
  studio/src/app/components/core/app-delete-deck-action/app-delete-deck-action.tsx
  studio/src/app/modals/core/app-deck-delete/app-deck-delete.scss
  studio/src/app/modals/core/app-deck-delete/app-deck-delete.tsx
  studio/src/app/modals/core/app-user-delete/app-user-delete.scss
  studio/src/app/modals/core/app-user-delete/app-user-delete.tsx
  studio/src/app/pages/core/app-dashboard/app-dashboard.scss
  studio/src/app/pages/core/app-dashboard/app-dashboard.tsx
  studio/src/app/services/data/deck/deck.service.tsx
  studio/src/components.d.ts
Labels: cloud, enhancement, studio

#320 breaking(#319): save screen shot in user new root folder
  cloud/functions/src/watch/screenshot/generate-deck-screenshot.ts
Labels: breaking

#323 Propagate deck delete to menu and dashboard
  studio/src/app/components/core/app-delete-deck-action/app-delete-deck-action.tsx
  studio/src/app/components/core/app-menu/app-menu.tsx
  studio/src/app/pages/core/app-dashboard/app-dashboard.scss
  studio/src/app/pages/core/app-dashboard/app-dashboard.tsx
  studio/src/components.d.ts
Labels: enhancement

#325 style(#324): improve tags style
  studio/src/app/components/feed/card/app-feed-card-tags/app-feed-card-tags.scss
  studio/src/app/components/feed/card/app-feed-card-tags/app-feed-card-tags.tsx
  studio/src/app/components/feed/card/app-feed-card/app-feed-card.tsx
Labels: enhancement

#329 fix: firebase not defined when deleting all content on a gif slide
  studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
Labels: bug

#330 feat: add dashboard link to (left pane) menu
  studio/src/app/components/core/app-menu/app-menu.tsx
Labels: enhancement, studio

#333 Optional src for the markdown webpack plugin
  CHANGELOG.md
  README.md
  docs/CHANGELOG.md
  docs/docs/edit/app-edit-markdown/app-edit-markdown.md
  docs/package-lock.json
  docs/package.json
  docs/src/app/pages/docs/edit/app-edit-markdown/app-edit-markdown.tsx
  webpack/CHANGELOG.md
  webpack/package-lock.json
  webpack/package.json
  webpack/src/markdown/deckdeckgo-markdown-plugin.ts
Labels: enhancement, webpack

#334 Feat: New "Big img" Slide component
  webcomponents/slides/big-img/.editorconfig
  webcomponents/slides/big-img/LICENSE
  webcomponents/slides/big-img/README.md
  webcomponents/slides/big-img/package-lock.json
  webcomponents/slides/big-img/package.json
  webcomponents/slides/big-img/showcase/big-deckdeckgo-h.jpg
  webcomponents/slides/big-img/showcase/big-deckdeckgo-h.xcf
  webcomponents/slides/big-img/showcase/big-deckdeckgo.jpg
  webcomponents/slides/big-img/showcase/big-deckdeckgo.xcf
  webcomponents/slides/big-img/src/components.d.ts
  webcomponents/slides/big-img/src/components/slide/deckdeckgo-slide-big-img.scss
  webcomponents/slides/big-img/src/components/slide/deckdeckgo-slide-big-img.tsx
  webcomponents/slides/big-img/src/components/slide/readme.md
  webcomponents/slides/big-img/src/index.html
  webcomponents/slides/big-img/src/index.ts
  webcomponents/slides/big-img/stencil.config.ts
  webcomponents/slides/big-img/tsconfig.json
Labels: templates

#336 Big img docs
  README.md
  docs/docs/slides/app-slide-big-img/app-slide-big-img.md
  docs/docs/slides/app-slides-concept/app-slides-concept.md
  docs/package-lock.json
  docs/package.json
  docs/src/app/app-root.tsx
  docs/src/app/pages/docs/slides/app-slide-big-img/app-slide-big-img.tsx
  docs/src/app/pages/docs/slides/app-slide-big-img/app-slides-big-img.scss
  docs/src/app/pages/docs/slides/app-slides-concept/app-slides-concept.tsx
  docs/src/app/pages/docs/slides/app-slides-container.scss
  docs/src/components.d.ts
  docs/src/global/app.ts
  webcomponents/slides/big-img/showcase/big-deckdeckgo-h.xcf
  webcomponents/slides/big-img/showcase/big-deckdeckgo.xcf
  webcomponents/slides/big-img/src/components.d.ts
  webcomponents/slides/big-img/src/components/slide/deckdeckgo-slide-big-img.scss
  webcomponents/slides/big-img/src/components/slide/deckdeckgo-slide-big-img.tsx
  webcomponents/slides/big-img/src/components/slide/readme.md
  webcomponents/slides/big-img/src/index.html
Labels: templates

#338 Remote play pause for videos
  CHANGELOG.md
  remote/CHANGELOG.md
  remote/package-lock.json
  remote/package.json
  remote/src/app/pages/app-remote/app-remote.tsx
  studio/CHANGELOG.md
  studio/package-lock.json
  studio/package.json
  studio/src/app/handlers/editor/events/remote/remote-events.handler.tsx
  webcomponents/remote/CHANGELOG.md
  webcomponents/remote/README.md
  webcomponents/remote/package-lock.json
  webcomponents/remote/package.json
  webcomponents/remote/src/components.d.ts
  webcomponents/remote/src/components/deckdeckgo-remote/deckdeckgo-remote.tsx
  webcomponents/remote/src/services/communication/communication.service.tsx
  webcomponents/types/CHANGELOG.md
  webcomponents/types/package-lock.json
  webcomponents/types/package.json
  webcomponents/types/src/index.ts
Labels: enhancement

#339 feat: improve avatars accessbility
  studio/src/app/components/core/app-avatar/app-avatar.tsx
  studio/src/app/components/core/app-navigation-actions/app-navigation-actions.tsx
  studio/src/app/components/core/app-user-info/app-user-info.tsx
  studio/src/app/components/feed/card/app-feed-card/app-feed-card.tsx
  studio/src/app/pages/core/about/app-team/app-team.tsx
  studio/src/app/pages/core/app-settings/app-settings.tsx
  studio/src/components.d.ts
Labels: enhancement, studio

#343 feat: update studio to publish content to new api
  studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
  studio/src/app/models/api/api.deck.tsx
  studio/src/app/models/api/api.presentation.tsx
  studio/src/app/models/api/api.slide.tsx
  studio/src/app/services/api/deck/api.deck.service.tsx
  studio/src/app/services/api/presentation/api.presentation.service.tsx
  studio/src/app/services/api/slide/api.slide.service.tsx
  studio/src/app/services/editor/publish/publish.service.tsx
Labels: enhancement, studio

#342 infra: update deckdeckgo starter
  infra/default.nix
  infra/dynamo.tf
  infra/handler/app/Handler.hs
  infra/handler/app/Presenter.hs
  infra/handler/app/Swagger.hs
  infra/handler/app/Test.hs
  infra/handler/package.yaml
  infra/handler/src/DeckGo/Handler.hs
  infra/handler/src/DeckGo/Presenter.hs
  infra/lambda.tf
  infra/nix/sources.json
  infra/presentation_lambda.tf
  infra/sqs.tf
Labels: api

#344 feat(#313): copy/clone slide
  studio/src/app/components/editor/actions/app-editor-actions/app-editor-actions.tsx
  studio/src/app/components/editor/actions/app-share-action/app-share-action.tsx
  studio/src/app/components/editor/app-editor-toolbar/app-editor-toolbar.scss
  studio/src/app/components/editor/app-editor-toolbar/app-editor-toolbar.tsx
  studio/src/app/helpers/editor/editor.helper.tsx
  studio/src/app/pages/core/app-dashboard/app-dashboard.tsx
  studio/src/app/pages/editor/app-editor/app-editor.tsx
  studio/src/app/popovers/editor/app-create-slide/app-create-slide.tsx
  studio/src/app/utils/editor/create-slides.utils.tsx
  studio/src/app/utils/editor/parse-slides.utils.tsx
  studio/src/components.d.ts
Labels: enhancement, studio

#354 feat(#353): use color picker to select code's colors
  studio/src/app/popovers/editor/app-code/app-code.tsx
Labels: enhancement, studio

#352 feat(#351): pass description to the publish
  studio/src/app/models/api/api.deck.tsx
  studio/src/app/services/editor/publish/publish.service.tsx
Labels: bug, studio

#357 infra: render presentation description
  infra/handler/app/Test.hs
  infra/handler/src/DeckGo/Handler.hs
Labels: api, bug

#361 feat: add a meta attribute for the display in the feed
  studio/src/app/models/data/deck.tsx
  studio/src/app/services/data/feed/feed.service.tsx
  studio/src/app/services/editor/publish/publish.service.tsx
Labels: enhancement, studio

#365 fix(#364): missing common presentations icons
  studio/src/assets/icons/deckdeckgo.svg
  studio/src/assets/icons/ionicons/clipboard.svg
  studio/src/assets/icons/ionicons/phone-portrait.svg
  studio/src/assets/icons/ionicons/share.svg
Labels: bug, starter, studio

#368 feat(#367): mock api
  CONTRIBUTING.md
  studio/src/app/components/core/app-user-info/app-user-info.tsx
  studio/src/app/components/editor/publish/app-publish-edit/app-publish-edit.tsx
  studio/src/app/definitions/unsplash.d.ts
  studio/src/app/modals/editor/app-photo/app-photo.tsx
  studio/src/app/pages/core/app-settings/app-settings.tsx
  studio/src/app/services/api/photo/api.photo.factory.service.tsx
  studio/src/app/services/api/photo/api.photo.mock.service.tsx
  studio/src/app/services/api/photo/api.photo.prod.service.tsx
  studio/src/app/services/api/photo/api.photo.service.tsx
  studio/src/app/services/api/presentation/api.presentation.factory.service.tsx
  studio/src/app/services/api/presentation/api.presentation.mock.service.tsx
  studio/src/app/services/api/presentation/api.presentation.prod.service.tsx
  studio/src/app/services/api/presentation/api.presentation.service.tsx
  studio/src/app/services/api/user/api.user.factory.service.tsx
  studio/src/app/services/api/user/api.user.mock.service.tsx
  studio/src/app/services/api/user/api.user.prod.service.tsx
  studio/src/app/services/api/user/api.user.service.tsx
  studio/src/app/services/auth/auth.service.tsx
  studio/src/app/services/core/environment/environment-config.tsx
  studio/src/app/services/editor/publish/publish.service.tsx
  studio/src/global/app-dev.ts
  studio/src/global/app.ts
Labels: api, enhancement, studio

#369 fix: docs typo deckgo-slide-countdown
  docs/docs/slides/app-slide-countdown/app-slide-countdown.md
  docs/src/app/pages/docs/slides/app-slide-countdown/app-slide-countdown.tsx
Labels: docs

#373 studio: opacity and reset color
  README.md
  docs/CHANGELOG.md
  docs/docs/components/app-components-color/app-components-color.md
  docs/package-lock.json
  docs/package.json
  docs/src/app/pages/docs/components/app-components-color/app-components-color.tsx
  studio/package-lock.json
  studio/package.json
  studio/src/app/popovers/editor/app-color/app-color.scss
  studio/src/app/popovers/editor/app-color/app-color.tsx
  studio/src/app/popovers/editor/app-image/app-image.scss
  studio/src/global/theme/editor/editor-popover.scss
  webcomponents/color/CHANGELOG.md
  webcomponents/color/package-lock.json
  webcomponents/color/package.json
  webcomponents/color/src/components.d.ts
  webcomponents/color/src/components/color/deckdeckgo-color.tsx
  webcomponents/color/src/components/color/readme.md
Labels: enhancement, studio

#374 studio: randomize feed
  studio/src/app/services/data/feed/feed.service.tsx
Labels: enhancement, studio

#375 lib: upgrade firebase
  studio/package-lock.json
  studio/package.json
Labels: studio

#377 feat(#376): consider only slots as content when saving slides
  studio/src/app/handlers/editor/events/deck/deck-events.handler.tsx
  studio/src/app/pages/editor/app-editor/app-editor.tsx
Labels: enhancement, studio
