Repository deckgo/deckdeckgo, pull requests merged in 2020-12, with the labels that each got.

#1028 split settings in two routes customization and profile
  studio/src/app/app-root.tsx
  studio/src/app/components/core/app-menu/app-menu.scss
  studio/src/app/components/core/app-menu/app-menu.tsx
  studio/src/app/components/editor/styles/app-expansion-panel/app-expansion-panel.scss
  studio/src/app/components/editor/styles/app-expansion-panel/app-expansion-panel.tsx
  studio/src/app/pages/core/settings/app-customization/app-customization.scss
  studio/src/app/pages/core/settings/app-customization/app-customization.tsx
  studio/src/app/pages/core/settings/app-profile/app-profile.scss
  studio/src/app/pages/core/settings/app-profile/app-profile.tsx
  studio/src/components.d.ts
Labels: enhancement, studio

#1029 style: avatar display and size in menu
  studio/src/app/components/core/app-menu/app-menu.tsx
  studio/src/app/components/core/app-user-info/app-user-info.scss
  studio/src/app/components/core/app-user-info/app-user-info.tsx
  studio/src/app/popovers/core/app-user-menu/app-user-menu.scss
  studio/src/components.d.ts
Labels: enhancement, studio

#1033 feat: goodfirms featured story
  studio/src/app/pages/core/about/app-press/app-press.tsx
Labels: enhancement, studio

#1032 highlightcode: alias support and show error if lang not supported
  webcomponents/highlight-code/scripts/config.languages.js
  webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.tsx
  webcomponents/highlight-code/src/declarations/deckdeckgo-highlight-code-languages.tsx
  webcomponents/highlight-code/src/index.html
Labels: enhancement, highlight-code

#1034 fix: required scripts loading race condition
  webcomponents/highlight-code/CHANGELOG.md
  webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.tsx
Labels: bug, highlight-code

#1037 fix: scope github actions backup
  .github/workflows/backup.yml
Labels: bug

#1039 feat: improve site
  site/src/assets/i18n/enterprise.json
  site/src/assets/i18n/index.json
  site/src/components/core/buttons/button.module.scss
  site/src/components/core/links/links.module.scss
  site/src/components/core/navigation/navigation.js
  site/src/components/core/navigation/navigation.module.scss
  site/src/components/enterprise/hero/hero.js
  site/src/components/enterprise/hero/hero.module.scss
  site/src/components/landing/deck/landing-deck.js
  site/src/pages/faq/index.en.js
  site/src/themes/theme.scss
Labels: enhancement

#1040 feat: minor site improveements
  site/src/components/core/footer/footer.js
  site/src/components/core/links/links.js
  site/src/components/core/menu/menu.js
  site/src/components/core/navigation/navigation.js
  site/src/components/landing/deck/landing-deck.js
  site/src/components/landing/deck/landing-deck.module.scss
  site/src/pages/opensource/index.en.js
Labels: enhancement

#1042 feat: github action to deploy site
  .github/workflows/site.yml
  site/gatsby-node.js
Labels: enhancement

#1043 fix: signin if already signedin from website
  studio/src/app/app-root.tsx
  studio/src/app/components/core/app-signin/app-signin.scss
  studio/src/app/components/core/app-signin/app-signin.tsx
  studio/src/app/components/dashboard/app-dashboard/app-dashboard.scss
  studio/src/app/components/dashboard/app-dashboard/app-dashboard.tsx
  studio/src/app/components/editor/app-slot-type/app-slot-type.scss
  studio/src/app/pages/core/app-dashboard/app-dashboard-page.tsx
  studio/src/app/pages/core/app-signin/app-signin-page.tsx
  studio/src/components.d.ts
Labels: bug

#1044 style: deck arrows navigation display on smaller device
  site/src/components/landing/deck/landing-deck.module.scss
Labels: enhancement
